module.exports = [
    {n:0,t:'Budget Esrog',p:50},
    {n:1,t:'Israeli set A PITOM',p:30},
    {n:1,t:'Israeli set B PITOM',p:25},
    {n:1,t:'Israeli set C PITOM',p:20},
    {n:1,t:'Israeli set A NO PITOM',p:30},
    {n:1,t:'Israeli set B NO PITOM',p:25},
    {n:1,t:'Israeli set C NO PITOM',p:20},
    {n:2,t:'Esrog Yannever A PITOM',p:300},
    {n:2,t:'Esrog Yannever B PITOM',p:200},
    {n:2,t:'Esrog Yannever C PITOM',p:150},
    {n:2,t:'Esrog Yannever D PITOM',p:100},
    {n:2,t:'Esrog Yannever A NO PITOM',p:300},
    {n:2,t:'Esrog Yannever B NO PITOM',p:200},
    {n:2,t:'Esrog Yannever C NO PITOM',p:150},
    {n:2,t:'Esrog Yannever D NO PITOM',p:100},
    {n:3,t:'Egyptian Lulav',p:15}, 
    {n:3,t:'Deri Lulav',p:25}, 
    {n:3,t:'Deri Much Lulav',p:40}, 
    {n:4,t:'Aruvos',p:3},
    {n:5,t:'Hadas A',p:15},
    {n:5,t:'Hadas B',p:10},
    {n:5,t:'Hadas C',p:5},
    {n:6,t:'Hushanos',p:5},
    {n:7,t:"Koisaklach",p:0},
    {n:7,t:"Plastic bag",p:0},
    {n:7,t:"Hadas C",p:0},
    {n:7,t:"Aruvos",p:0},
    {n:7,t:"Egyptian Lulav",p:0},
    {n:8,t:"Koisaklach",p:0},
    {n:8,t:"Plastic bag",p:0},
    {n:8,t:"Hadas B",p:0},
    {n:8,t:"Hadas C",p:0},
    {n:8,t:"Aruvos",p:0},
    {n:8,t:"Egyptian Lulav",p:0}
]
